version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    ports:
      - '8888:8080'
    restart: always
  front:
    build: ./frontend
    ports:
      - '3000:3000'
    restart: always
  api:
    build: ./api
    ports:
      - '5555:5000'
    restart: always
    depends_on:
      mysql:
        condition: service_healthy